# https://taskfile.dev

version: '3'

silent: false

tasks:
  default:
    cmds:
      - task --list
    silent: true

  install:
    cmds:
      - npm install

  build:
    cmds:
      - npm run build

  test:
    cmds:
      - npm run test
