name: Build

"on":
  push:
    branches:
    - '*'
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: chill-viking/npm-ci@latest
        name: Install dependencies

      - name: Test
        id: test
        run: |
          npm run test

      - name: Build
        if: steps.test.outcome == 'success'
        run: |
          npm run build
