name: Build and Test

"on":
  push:
    branches:
    - '*'
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: chill-viking/npm-ci@latest
        name: Install dependencies

      - name: Test
        id: test
        run: |
          npm run test
        continue-on-error: true

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: ./reports

      - name: Build
        if: steps.test.outcome == 'success'
        run: |
          npm run build
